AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/**/*
    - exe/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/SpaceInLambdaLiteral:
  Enabled: false
